apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 30s
      receiver: 'email-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'email-notifications'
    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'semensoniao@gmail.com'
        from: 'semensoniao@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'semensoniao@gmail.com'
        auth_password: T0JBTUJJU0VtRTYK # This will be replaced by the secret
        auth_identity: 'semensoniao@gmail.com'
        send_resolved: true
        require_tls: true
